/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Asti
 */
public class LaporanInventarisMasuk extends javax.swing.JInternalFrame {

    private Connection con;
private void kosongkan_form(){
        txt_iduser.setEditable(true);
        txt_iduser.setText(null);
        txt_inventarismasuk.setText(null);
        txt_kdbarang.setText(null);
        txt_namabrg.setText(null);
        txt_jenis.setText(null);
        txt_kdlokasi.setText(null);
        txt_jumlah.setText(null);
        txt_nilai.setText(null);
        txt_namauser.setText(null);
        txt_tglmasuk.setText(null);
    }
    
    private void tampilkan_data(){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No.");
    model.addColumn("Id User");
    model.addColumn("Id Inventaris");
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Jenis");
    model.addColumn("Kode Lokasi");
    model.addColumn("Jumlah");
    model.addColumn("Nilai Barang");
    model.addColumn("Nama User");
    model.addColumn("Tanggal Masuk");
    
    try{
        int no = 1;
        String sql = "SELECT * FROM invetaris_masuk";
        java.sql.Connection conn = (Connection)Konfig.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
        }
        tabel_inventarismasuk.setModel(model);
    }catch (SQLException e){
        System.out.println("Error : "+e.getMessage());
    }
    }
    /**
     * Creates new form LaporanInventarisKantor
     */
    public LaporanInventarisMasuk() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_inventarismasuk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_iduser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_inventarismasuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kdbarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_namabrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_jenis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_kdlokasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nilai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_namauser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tglmasuk = new javax.swing.JTextField();

        setTitle("Laporan Inventaris Masuk");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("LAPORAN INVENTARIS MASUK");

        btn_cetak.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cetak.setText("CETAK");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        tabel_inventarismasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tabel_inventarismasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_inventarismasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_inventarismasuk);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Id User");

        txt_iduser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Id Inventaris Masuk");

        txt_inventarismasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kode Barang");

        txt_kdbarang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nama Barang");

        txt_namabrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Jenis");

        txt_jenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kode Lokasi");

        txt_kdlokasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Jumlah");

        txt_jumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Nilai Barang");

        txt_nilai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nama User");

        txt_namauser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal Masuk");

        txt_tglmasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_inventarismasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_namabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_kdlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 252, Short.MAX_VALUE))
                                            .addComponent(txt_jenis))))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_namauser, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_cetak)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(91, 91, 91)))
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_namauser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_inventarismasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_tglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_namabrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_kdlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_cetak)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
       java.sql.Connection con = null;
       try{
           String jdbcDriver = "com.mysql.jdbc.Driver";
           Class.forName(jdbcDriver);
           
           String url = "jdbc:mysql://localhost/dbinventori";
           String user = "root";
           String pass = "";
           
           con = DriverManager.getConnection(url, user, pass);
           Statement stm = con.createStatement();
           
           try{
               String report = ("C:\\Users\\Asti\\Documents\\JAVA\\JavaApplication\\src\\Aplikasi\\laporaninventarismasuk.jrxml");
               HashMap hash = new HashMap();
               
               hash.put("kode", txt_iduser.getText());
               JasperReport JRpt = JasperCompileManager.compileReport(report);
               JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
               JasperViewer.viewReport(JPrint, false);
           } catch(Exception rptexcpt){
               System.out.println("Report Can't view Because :" + rptexcpt);
           }
       }catch (Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void tabel_inventarismasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_inventarismasukMouseClicked
        // TODO add your handling code here:
        int baris = tabel_inventarismasuk.rowAtPoint(evt.getPoint());
        String id_user = tabel_inventarismasuk.getValueAt(baris, 1).toString();
        txt_iduser.setText(id_user);
        
        String inventarismasuk = tabel_inventarismasuk.getValueAt(baris, 2).toString();
        txt_inventarismasuk.setText(inventarismasuk);
        
        String kodebrg = tabel_inventarismasuk.getValueAt(baris, 3).toString();
        txt_kdbarang.setText(kodebrg);
        
        String namabrg = tabel_inventarismasuk.getValueAt(baris, 4).toString();
        txt_namabrg.setText(namabrg);
        
        String jenis = tabel_inventarismasuk.getValueAt(baris, 5).toString();
        txt_jenis.setText(jenis);
        
        String kdlokasi = tabel_inventarismasuk.getValueAt(baris, 6).toString();
        txt_kdlokasi.setText(kdlokasi);
        
        String jumlah = tabel_inventarismasuk.getValueAt(baris, 7).toString();
        txt_jumlah.setText(jumlah);
        
        String nilai = tabel_inventarismasuk.getValueAt(baris, 8).toString();
        txt_nilai.setText(nilai);
        
        String nama_user = tabel_inventarismasuk.getValueAt(baris, 9).toString();
        txt_namauser.setText(nama_user);
        
        String tglmsk = tabel_inventarismasuk.getValueAt(baris, 10).toString();
        txt_tglmasuk.setText(tglmsk);
    }//GEN-LAST:event_tabel_inventarismasukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_inventarismasuk;
    private javax.swing.JTextField txt_iduser;
    private javax.swing.JTextField txt_inventarismasuk;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kdbarang;
    private javax.swing.JTextField txt_kdlokasi;
    private javax.swing.JTextField txt_namabrg;
    private javax.swing.JTextField txt_namauser;
    private javax.swing.JTextField txt_nilai;
    private javax.swing.JTextField txt_tglmasuk;
    // End of variables declaration//GEN-END:variables
}
